buildscript {
    ext.kotlin_version = '1.9.22'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.3.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"

    afterEvaluate {
        if (project.hasProperty("android")) {
            def android = project.android

            // Only configure if not already set
            if (android.compileSdkVersion == null) {
                android.compileSdkVersion 34
            }

            if (android.defaultConfig.minSdkVersion == null) {
                android.defaultConfig.minSdkVersion 21
            }
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
