buildscript {
    ext.kotlin_version = '1.9.22'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.3.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

// Configure all Android plugin subprojects
subprojects {
    project.plugins.withType(com.android.build.gradle.BasePlugin).configureEach {
        project.extensions.configure(com.android.build.api.dsl.CommonExtension) {
            compileSdk = 34

            defaultConfig {
                minSdk = 21
            }

            compileOptions {
                sourceCompatibility = JavaVersion.VERSION_17
                targetCompatibility = JavaVersion.VERSION_17
            }
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
